.TH FREETENNIS 8 "July 17, 2007"
.SH NAME
freetennis \- free tennis simulation game
.SH SYNOPSIS
.B freetennis
.RI [ options ]
.SH DESCRIPTION
Free Tennis is a free tennis simulation game.
.PP
.SH OPTIONS
A summary of options is included below.
.TP
.B \-help, \-\-help
Show summary of options.
.TP
.B \-newbie
Make the game not realistic, but more suited to newbies.  The parabola is fully visible.
.SH SEE ALSO
http://freetennis.sourceforge.net/
.br
/usr/share/doc/freetennis-common/web-site/index.html
.SH AUTHOR
freetennis was written by Maurizio Colucci <maurizio.colucci@gmail.com>.
.PP
This manual page was written by Bart Martens <bartm@knars.be>,
for the Debian project (but may be used by others).
